version: "3.3"

services:
  camunda:
    container_name: camunda
    build: .
    ports:
      - 8080:8080
    # environment:
    #   - JAEGER_SERVICE_NAME=camunda
    #   - JAEGER_AGENT_HOST=jaeger
    #   - JAEGER_AGENT_PORT=6831
    #   - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    #   - JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"

  # jaeger:
  #   container_name: jaeger
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - 5775:5775/udp
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 5778:5778
  #     - 16686:16686
  #     - 14268:14268
  #     - 9411:9411

